name: Deploy to GitHub Pages

on:
  # Se ejecuta cada vez que haces push a la rama 'main'
  push:
    branches: [main]
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para que GitHub Actions publique en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: 22 # Modificado para usar la versión 22
        # with:
        # node-version: 20 # Descomenta esta línea si necesitas una versión específica de Node
        # package-manager: npm # Opcional: Astro lo detecta automáticamente por tu package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
